config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations' 
  }

  resources :events do
    member do
      # events/:id/participate
      post :participated
      post :unparticipated
    end

    collection do
      get :draft
      get :public
    end

    resources :comments, only: [:create]
  end

 
  resources :users, only: [] do
    member do
      # users/:id/follow
      post :follow
    end
  end

  namespace :dashboard do 
    get 'welcome', to: 'welcome#index'
    resources :events, only: [:index, :destroy]
    resources :users, only: [:index, :destroy]
  end

  # /@username
  get '@:username', to: 'welcome#user', as: 'user_page'
  get '@:username/followers', to: 'welcome#followers', as: 'followers_user'
  get '@:username/followings', to: 'welcome#followings', as: 'followings_user'

end

app/views/shared/_cover_image.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <% if event.images.attached? %>

    <ol class="carousel-indicators">
      <% event.images.each_with_index do |image, index| %>
        <li data-target="#carouselExampleIndicators" data-slide-to="#{index}" <%= index == 0 ? 'class="active"' : '' %></li>
      <% end %>  
    </ol>

    <div class="carousel-inner">
      <% event.images.each_with_index do |image, index| %>
        <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
          <%= image_tag image, class: "d-block w-100 img-cover" %>
        </div>
      <% end %>
    </div>
        
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>

  <% end %>
</div>

app/views/shared/_dashboard_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <%= link_to "DashBoard", dashboard_welcome_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
    aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= link_to "GoClimbing", root_path, class: "nav-link" %>
      </li>
      <div class="dropdown-divider"></div>

      <li class="nav-item">
        <%= link_to "Log Out", destroy_user_session_path, class: "nav-link",
                               method: :delete, data: { confirm: "Are you sure?" } %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_flash.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong><%= notice %></strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/shared/_footer.html.erb
<footer class="container-fluid navbar-fixed-bottom">

  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="#"> goclimbing.com</a>
  </div>

</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "GoClimbing", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <% if current_user.avatar.attached? %>
              <%= avatar(current_user, 35) %>
            <% else %>
              <%= current_user.email %>
            <% end %>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Events", draft_events_path, class: "dropdown-item" %>
            <%= link_to "Profile", user_page_path(current_user.username), class: "dropdown-item" %>
            <%= link_to "Setting", edit_user_registration_path(current_user), class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <% if current_user.admin? %>
              <%= link_to "Dashboard", dashboard_welcome_path, class: "dropdown-item" %>
            <% end %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, 
                data: { confirm: "Are you sure?" }, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
      <% end %>
    </ul>
    
  </div>
</nav>

app/views/shared/_participate.html.erb
<% if user_signed_in? && current_user != event.user %>
  <% if event.is_participated?(current_user) %>
    <%= link_to "Unparticipated", unparticipated_event_path(event), method: :post,
                        class: "btn btn-outline-info" %>
  <% else %>
    <%= link_to "Participate", participated_event_path(event), method: :post,
                      class: "btn btn-info" %>
  <% end %>
<% end %>

app/views/shared/_root_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "GoClimbing", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <form class="form-inline my-2 my-lg-0">
      <%= form_tag root_path, method: :get do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control mr-sm-2" %>
        <%= submit_tag "Search", class: "btn btn-outline-success my-2 my-sm-0", name: nil %>
      <% end %>
    </form>

    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <% if current_user.avatar.attached? %>
            <%= avatar(current_user, 35) %>
          <% else %>
            <%= current_user.email %>
          <% end %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Events", draft_events_path, class: "dropdown-item" %>
          <%= link_to "Profile", user_page_path(current_user.username), class: "dropdown-item" %>
          <%= link_to "Setting", edit_user_registration_path(current_user), class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <% if current_user.admin? %>
            <%= link_to "Dashboard", dashboard_welcome_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, 
                data: { confirm: "Are you sure?" }, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
        <%= link_to "Sing Up", new_user_registration_path, class: "nav-link" %>
        <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
      <% end %>
    </ul>

  </div>
</nav>