config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations' 
  }

  resources :events do
    member do
      # events/:id/participate
      post :participated
      post :unparticipated
    end

    collection do
      get :draft
      get :public
    end

    resources :comments, only: [:create]
  end

 
  resources :users, only: [] do
    member do
      # users/:id/follow
      post :follow
    end
  end

  namespace :dashboard do 
    get 'welcome', to: 'welcome#index'
    resources :events, only: [:index, :destroy]
    resources :users, only: [:index, :destroy]
  end

  # /@username
  get '@:username', to: 'welcome#user', as: 'user_page'
  get '@:username/followers', to: 'welcome#followers', as: 'followers_user'
  get '@:username/followings', to: 'welcome#followings', as: 'followings_user'

end

app/controllers/dashboard/welcome_controller.rb
class Dashboard::WelcomeController < Dashboard::BaseController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout "search", only: :index
  before_action :find_user, except: :index

  def index
    if params[:search]
      @events = Event.published.not_overdue.where('title LIKE ? OR location LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%").includes(:user)
    else
      @newest_events = Event.published.not_overdue.order(created_at: :desc).includes(:user).limit(20)
      @papular_events = Event.published.not_overdue.order(participates_count: :desc).includes(:user).limit(5)
    end
  end
  
  def user
    @events = @user.events.published.not_overdue.order(date: :desc).includes(:user)
    @participated_events = @user.participated_events.published.not_overdue.order(date: :desc).includes(:user)
    @overdue_participated_events = @user.participated_events.published.overdue.order(date: :desc).includes(:user)
  end

  def followers
    @followers = @user.followers
  end

  def followings
    @followings = @user.followings
  end

  private
  def find_user
    @user = User.find_by(username: params[:username])
  end
end

app/views/welcome/_welcome_events.html.erb
<% events.each do |event| %>
  <%= link_to event_path(event), class: "text-dark text-decoration-none" do %>
    <b><%= event.title %></b>
    <small class="text-muted"><%= event.date %></small><br/>
  <% end %>
<% end %>

app/views/welcome/followers.html.erb
<% @followers.each do |follower| %>
  <%= link_to follower.username, user_page_path(follower.username) %>
<% end %>

app/views/welcome/followings.html.erb
<% @followings.each do |following| %>
  <%= link_to following.username, user_page_path(following.username) %>
<% end %>

app/views/welcome/index.html.erb
<!-- All of the Events -->
  <div class="row">
    <div class="col-lg-8 col-md-8 col-sm-12">
      <h4 class="text-muted text-tag">Newest Events</h4>
      <% @newest_events.each do |event| %>
        <div class="newest_content">
          <%= link_to event_path(event), class: "text-dark text-decoration-none" do %>
            <h1><%= event.title %></h1>
            <span><%= image_tag event.images.first.variant(resize_to_limit: [150, 100]), class: "float-right index-image" if event.images.attached? %></span>
            <%= event.location %>
            <%= event.date %>
            <p class="text-break"><%= truncate(event.content, length: 150) %></p>
            Participates <b><%= event.participates.size %></b>
          <% end %>
          <%= render partial: "shared/participate", locals: { event: event } %>
        </div>
        <hr>
      <% end %>
      
      <% unless @newest_events.count < 15 %>
        <%= link_to "See More...", events_path, class: "float-right text-dark text-decoration-none" %>
      <% end %>
    </div>
  
    <div class="col-lg-4 col-md-4 col-sm-12">
      <!-- Most of Searching -->
      
      <!-- Participated Top -->
      <h6 class="text-muted text-tag text-center">Popular for People</h6>
      <hr>
      <% @papular_events.each_with_index do |event, index| %>
        <div class="papular-content">
          <span class="text-muted text-number"><%= index + 1 %></span>
          <%= link_to event_path(event), class: "text-dark text-decoration-none" do %>
            <span class="popular-text"><%= event.title %></span>
          <% end %>
        </div>
      <% end %>
    </div>
  
  </div>

app/views/welcome/user.html.erb
<!-- User Profile -->
<div class="user-content">
  <div class="row justify-content-md-center">
    <div class="col-lg-8 col-md-10 col-sm-12" data-controller="user">
      <%= avatar(@user, 150) %>
      <h2 class="profile">
        <%= @user.username %>
        <%= link_to "#", class: "btn btn-secondary follow-button",
                          data: { action: "user#follow",
                                  user: @user.id, 
                                  target: "user.followButton" } do %>
          <%= (user_signed_in? && current_user.follow?(@user)) ? 'Followed' : 'Follow' %>
        <% end %>
      </h2>
      <p><%= simple_format(@user.intro) %></p>
      <p>
        Events <b><%= @user.events.count %></b>
        
        Followers 
        <b>
          <%= link_to "#", class: "text-dark text-decoration-none",
                            data: { action: "user#follower",
                                      user: @user.username,
                                    target: "user.followerButton"} do %> 
            <%= @user.followers.size %>
          <% end %>
        </b>
        
        Followings 
        <b>
          <%= link_to "#", class: "text-dark text-decoration-none",
                                      data: { action: "user#following",
                                                user: @user.username,
                                              target: "user.followingButton"} do %>
            <%= @user.followings.size %>
          <% end %>
        </b>
      </p>
    </div>
    <div class="clearfix"></div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-lg-10 col-md-10 col-sm-12">
      <hr>
    </div>
  </div>  
</div>

<!-- User's Events -->
<div class="user-events">
  <div class="row justify-content-md-center">
    <% if user_signed_in? && current_user == @user %>
      <div class="col-lg-10 col-md-10 col-sm-12">
        <!-- Event by owner -->
        <div class="row">
          <div class="col-lg-8 col-md-8 col-sm-12">
            <% @events.each do |event| %>
              <%= link_to event_path(event), class: "text-dark text-decoration-none" do %>
                <div class="card">
                  <div class="card-body">
                    <h4>
                      <%= event.title %>
                      <small class="text-muted"><%= event.date %></small>
                    </h4>
                    <p><%= truncate((event.content), length: 100) %></p>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
          <hr>
          <div class="col-lg-4 col-md-4 col-sm-12">
            <!-- Events which owner participeted -->
            <div class="col-12">
              <%= render "welcome_events", events: @participated_events %>
            </div>
            <hr>
            <!-- Events which owner participated, but overdue -->
            <div class="col-12">
              <%= render "welcome_events", events: @overdue_participated_events %>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <div class="col-lg-8 col-md-8 col-sm-12">
        <% @events.each do |event| %>
          <%= link_to event_path(event), class: "text-dark text-decoration-none" do %>
            <h4>
              <%= event.title %>
              <small class="text-muted"><%= event.date %></small>
            </h4>
            <p><%= truncate((event.content), length: 100) %></p>
          <% end %>
          <hr>
        <% end %>
      </div>
    <% end %>
  </div>
</div>