config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations' 
  }

  resources :events do
    member do
      # events/:id/participate
      post :participated
      post :unparticipated
    end

    collection do
      get :draft
      get :public
    end

    resources :comments, only: [:create]
  end

 
  resources :users, only: [] do
    member do
      # users/:id/follow
      post :follow
    end
  end

  namespace :dashboard do 
    get 'welcome', to: 'welcome#index'
    resources :events, only: [:index, :destroy]
    resources :users, only: [:index, :destroy]
  end

  # /@username
  get '@:username', to: 'welcome#user', as: 'user_page'
  get '@:username/followers', to: 'welcome#followers', as: 'followers_user'
  get '@:username/followings', to: 'welcome#followings', as: 'followings_user'

end

app/models/event.rb
class Event < ApplicationRecord
  include AASM
  
  # Validations
  validates :title, presence: true
  
  # Relationships
  belongs_to :user

  has_many :participates, dependent: :destroy
  has_many :participated_users, through: :participates, source: :user

  has_many :comments, dependent: :destroy

  has_many_attached :images

  # AASM
  aasm(column: 'status', no_direct_assignment: true) do
    state :draft, initial: true
    state :published

    event :publish do
      transitions from: :draft, to: :published
    end

    event :unpublish do
      transitions from: :published, to: :draft
    end
  end

  def is_participated?(user)
    self.participated_users.include?(user)
  end

  scope :not_overdue, -> { where(['date > ?', Time.now])}
  scope :overdue, -> { where(['date < ?', Time.now])}
end

app/controllers/dashboard/events_controller.rb
class Dashboard::EventsController < Dashboard::BaseController
  def index
    @events = Event.published.order(created_at: :desc)
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to dashboard_events_path, notice: "Event already deleted."
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_event, except: [:index, :new, :create, :draft, :public]
  before_action :count_events, only: [:draft, :public]

  def index
    if params[:search]
      @events = Event.published.not_overdue.where('title LIKE ? OR location LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%").includes(:user)
    else
      @events = Event.published.not_overdue.order(created_at: :desc).includes(:user).page(params[:page]).per(15)
    end
  end

  def new
    @event = current_user.events.new
  end

  def create
    @event = current_user.events.new(event_params)
    @event.publish! if params[:publish]

    if @event.save
      if params[:publish]
        redirect_to public_events_path, notice: "Created new events."
      else
        redirect_to draft_events_path, notice: "Saved the events."
      end
    else
      render new_event_path, notice: "Please create again."
    end
  end

  def edit
    unless current_user == @event.user
      redirect_to root_path, notice: "You don't allow do it！"
    end
  end
  
  def update
    if @event.update(event_params)
      case
      when params[:publish]
        @event.publish!
        redirect_to public_events_path, notice: "Publish."
      when params[:unpublish]
        @event.unpublish!
        redirect_to draft_events_path, notice: "Unpublish."
      else
        redirect_to draft_events_path, notice: "Saved the event."
      end
    else
      render edit_event_path(@event), notice: "Please edit again."
    end
  end

  def show
    @comment = @event.comments.new
    @comments = @event.comments.order(created_at: :desc).includes(:user)
  end

  def destroy
    if @event.destroy
      redirect_back(fallback_location: root_path)
    end
  end

  def participated
    @event.participates.create!(user: current_user)
    redirect_back(fallback_location: root_path)
  end

  def unparticipated
    participated = Participate.where(event: @event, user: current_user)
    participated.destroy_all
    redirect_back(fallback_location: root_path)
  end

  def draft
    @draft_events = Event.where(status: "draft", user: current_user).order(created_at: :desc)
  end

  def public 
    @public_events = Event.where(status: "published", user: current_user).order(created_at: :desc)
  end

  private

  def event_params
    params.require(:event).permit(:title, :content, :note, :date, :location, :gather_location, images: [])
  end

  def find_event
    @event = Event.find(params[:id])
  end

  def count_events
    @draft_count = Event.where(status: "draft", user: current_user).count
    @public_count = Event.where(status: "published", user: current_user).count
  end
end

app/views/events/_comment.html.erb
<div class="card">
  <div class="card-body">
    <article class="comment">
      <span class="profile avatar-50">
        <div class="float-left">
          <%= link_to user_page_path(comment.user.username) do %>
            <%= avatar(comment.user, 50) %>
          <% end %>
        </div>
      </span>
      <p class="float-left card-text">
        <%= simple_format(comment.content) %>
      </p>
      <i class="float-left card-text text-muted">
        <% if Time.now - comment.created_at > 1.day %>
          <small><%= comment.created_at.strftime('%F') %></small>
        <% else %>
          <small><%= time_ago_in_words(comment.created_at) %></small>
        <% end %>
      </i>
      <div class="clearfix"></div>
    </article>
  </div>
</div>

app/views/events/_comment_area.html.erb
<section class="comment-editor">
  <% if user_signed_in? %>
    <%= form_with model: comment, url: event_comments_path(event), class: "comment_form", remote: true do |f| %>
    <div class="form-group">
      <%= f.text_area :content, rows: 5, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit "Submit", class: "btn btn-info btn-block btn-text" %>
    </div>
    <% end %>
  <% end %>
</section>

app/views/events/_form.html.erb
<div class="row justify-content-md-center">
  <div class="col-lg-8 col-md-10 col-sm-12 align-self-center">
    
    <%= form_with model: event do |f| %>
      <div class="form-group">
        <%= f.label :title, "Title", class: "label-text" %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :images, "Images", class: "label-text" %>
        <%= f.file_field :images, multiple: true %>
      </div>
    
      <div class="form-group">
        <%= f.label :date, "Date", class: "label-text" %>
        <%= f.date_field :date, class: "form-control" %>
      </div>
    
      <div class="form-group">
        <%= f.label :location, "Location", class: "label-text" %>
        <%= f.text_field :location, class: "form-control" %>
      </div>
    
      <div class="form-group">
        <%= f.label :gather_location, "Meeting Point", class: "label-text" %>
        <%= f.text_field :gather_location, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :note, "Reminder", class: "label-text" %>
        <%= f.text_area :note, class: "form-control" %>
      </div>
    
      <div class="form-group">
        <%= f.label :content, "Content", class: "label-text" %>
        <%= f.text_area :content, rows: "10", class: "form-control" %>
      </div>
      
      <div class="action">
        <%= f.submit :Draft, name: "save_as_draft", class: "btn btn-info btn-text" %>
        <%= f.submit :Publish, name: "publish", class: "btn btn-success btn-text" if event.may_publish? %>
        <%= f.submit :Unpublish, name: "unpublish", class: "btn btn-danger btn-text" if event.may_unpublish? %>
      </div>
    <% end %>

  </div>
</div>

app/views/events/draft.html.erb
<h2>
  Your Events
  <span class="float-right">
    <%= link_to "Create Event", new_event_path, class: "btn btn-secondary btn-large" %>
  </span>
</h2>


<ul class="nav nav-tabs nav-margin">
  <li class="nav-item">
    <%= link_to draft_events_path, class: "text-dark text-decoration-none nav-link active" do %>
      Drafts <%= @draft_count %>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to public_events_path, class: "text-dark text-decoration-none nav-link" do %>
      Published <%= @public_count %>
    <% end %>
  </li>
</ul>

<div class="event-content">
  <% @draft_events.each do |event| %>
    <h3><%= link_to event.title, event_path(event), class: "text-dark text-decoration-none" %></h3>
    <%= event.status %>
    <small class="text-muted">Last edited from <%= time_ago_in_words(event.updated_at) %>
      <span class="btn-group">
        <button class="btn btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false"></button>
        <div class="dropdown-menu">
          <%= link_to "Edit", edit_event_path(event), class: "dropdown-item" %>
          <%= link_to "Delete", event_path(event), class: "dropdown-item", 
                                method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
      </span>
    </small>
    <hr>
  <% end %>
</div>

app/views/events/edit.html.erb
<%= render 'events/form', event: @event %>

app/views/events/index.html.erb
<% content_for :navbar do %>
  <%= render "shared/root_navbar" %>
<% end %>

<div class="row justify-content-center">
  <% @events.each do |event| %>
    <%= link_to event_path(event), class: "text-dark text-decoration-none" do %>
      <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="card" style="width: 18rem;">
          <%= image_tag event.images.first, class: "card-img-top img-responsive center-block" if event.images.attached? %>
          <div class="card-body">
            <h5 class="card-title">
              <%= event.title %>
              <small class="text-muted text-date"><i><%= event.date %></i></small>
            </h5>
            <p class="card-text"><%= truncate(event.content, length: 200) %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <%= paginate @events %>
  <div class="clearfix"></div>
</div>

app/views/events/new.html.erb
<%= form_with model: Event.new do |f| %>
  <%= f.label :title, "標題" %>
  <%= f.text_field :title %>

  <%= f.label :date, "日期" %>
  <%= f.text_field :date %>

  <%= f.label :location, "地點" %>
  <%= f.text_field :location %>

  <%= f.label :gather_location, "集合地點" %>
  <%= f.text_field :gather_location %>

  <%= f.label :content, "提案內容" %>
  <%= f.text_area :content %>

  <%= f.label :note, "提醒事項" %>
  <%= f.text_area :note %>

  <%= f.submit "建立" %>
<% end %>

app/views/events/public.html.erb
<h2>
  Your Events
  <span class="float-right">
    <%= link_to "Create Event", new_event_path, class: "btn btn-secondary btn-large" %>
  </span>
</h2>


<ul class="nav nav-tabs nav-margin">
  <li class="nav-item">
    <%= link_to draft_events_path, class: "text-dark text-decoration-none nav-link" do %>
      Drafts <%= @draft_count %>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to public_events_path, class: "text-dark text-decoration-none nav-link active" do %>
      Published <%= @public_count %>
    <% end %>
  </li>
</ul>

<div class="event-content">
  <% @public_events.each do |event| %>
    <h3><%= link_to event.title, event_path(event), class: "text-dark text-decoration-none" %></h3>
    <small class="text-muted">
      <%= event.status %> from <%= event.created_at.strftime('%F') %>
      <span class="btn-group">
        <button class="btn btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false"></button>
        <div class="dropdown-menu">
          <%= link_to "Edit", edit_event_path(event), class: "dropdown-item" %>
          <%= link_to "Delete", event_path(event), class: "dropdown-item", 
                                method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
      </span>
    </small>
    <hr>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="row justify-content-center">
  <div class="col-lg-12 col-md-12 col-sm-12">
    <div class="row">
      <%= render "shared/cover_image", event: @event %>
    </div>
  </div>
    
  <div class="col-lg-10 col-md-10 col-sm-12">
    <div class="row">
      <!-- Event Contain -->
      <div class="col-lg-8 col-md-8 col-sm-12">
        <h2>
          <%= @event.title %>
          <span class="float-right">
            <%= render partial: "shared/participate", locals: { event: @event } %>
          </span>
        </h2>
        <h4><%= link_to @event.user.username, user_page_path(@event.user.username),
                                              class: "text-dark text-decoration-none" %></h4>
        <p><b>Date：</b><%= @event.date %></p>
        <p><b>Participates：</b><%= @event.participates.size %></p>
        <p><b>Mountain Name：</b><%= @event.location %></p>
        <p><b>Meeting Point：</b><%= @event.gather_location %></p>
        <p><b>Reminder：</b><%= simple_format(@event.note) %></p>
        <p><b>Content：</b><%= simple_format(@event.content, class: "text-break") %></p>
        <%= link_to "Back", :back, class: "btn btn-secondary" %>
      </div>

      <!-- Event participater -->
      <div class="col-lg-4 col-md-4 col-sm-12 overflow-auto">
        <h5 class=""><b>Participates：</b></h5>
        <% @event.participates.each do |participate| %>
          <div>
            <%= link_to user_page_path(participate.user.username), class: "text-dark text-decoration-none" do %>
              <div class="avatar-space">
                <span class="name-avatar"><%= avatar(participate.user, 50) %></span>
              </div>
              <span class="name-participater"><%= participate.user.username.split.first %></span>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<hr>

<!-- Comments -->
<div class="row justify-content-md-center">
  <div class="col-lg-6 col-md-8 col-sm-12">
    <section class="comments">
      <h4>Comment</h4>
      <%= render "comment_area", event: @event, comment: @comment %>
      <section class="comment-list">
        <%= render partial: "comment", collection: @comments %>
      </section>
    </section>
  </div>
</div>